package org.talend.designer.codegen.translators.business.microsoft_crm;

import java.util.List;
import java.util.Map;
import java.util.HashMap;
import org.talend.core.model.metadata.IMetadataColumn;
import org.talend.core.model.metadata.IMetadataTable;
import org.talend.core.model.metadata.types.JavaType;
import org.talend.core.model.metadata.types.JavaTypesManager;
import org.talend.core.model.process.ElementParameterParser;
import org.talend.core.model.process.IConnection;
import org.talend.core.model.process.IConnectionCategory;
import org.talend.core.model.process.INode;
import org.talend.designer.codegen.config.CodeGeneratorArgument;

public class TMicrosoftCrmInputBeginJava
{
  protected static String nl;
  public static synchronized TMicrosoftCrmInputBeginJava create(String lineSeparator)
  {
    nl = lineSeparator;
    TMicrosoftCrmInputBeginJava result = new TMicrosoftCrmInputBeginJava();
    nl = null;
    return result;
  }

  public final String NL = nl == null ? (System.getProperties().getProperty("line.separator")) : nl;
  protected final String TEXT_1 = "int nb_line_";
  protected final String TEXT_2 = " = 0;";
  protected final String TEXT_3 = NL + "\t\t" + NL + "\t\t\tSystem.setProperty(\"org.apache.commons.logging.Log\", \"org.apache.commons.logging.impl.NoOpLog\");" + NL + "\t\t\tcom.microsoft.crm4.webserviceTest.CrmServiceStub service_";
  protected final String TEXT_4 = " = new com.microsoft.crm4.webserviceTest.CrmServiceStub(";
  protected final String TEXT_5 = ");" + NL + "\t\t\torg.apache.axis2.client.Options options_";
  protected final String TEXT_6 = " = service_";
  protected final String TEXT_7 = "._getServiceClient().getOptions();" + NL + "\t\t\torg.apache.axis2.transport.http.HttpTransportProperties.Authenticator auth_";
  protected final String TEXT_8 = " = new org.apache.axis2.transport.http.HttpTransportProperties.Authenticator();" + NL + "\t\t\t" + NL + "\t\t\tList<String> authSchemes_";
  protected final String TEXT_9 = " = new java.util.ArrayList<String>();" + NL + "\t\t\tauthSchemes_";
  protected final String TEXT_10 = ".add(org.apache.axis2.transport.http.HttpTransportProperties.Authenticator.NTLM);" + NL + "\t\t\tauth_";
  protected final String TEXT_11 = " .setAuthSchemes(authSchemes_";
  protected final String TEXT_12 = ");" + NL + "\t\t\t" + NL + "            auth_";
  protected final String TEXT_13 = " .setUsername(";
  protected final String TEXT_14 = ");" + NL + "            auth_";
  protected final String TEXT_15 = " .setPassword(";
  protected final String TEXT_16 = ");" + NL + "            auth_";
  protected final String TEXT_17 = " .setHost(";
  protected final String TEXT_18 = ");" + NL + "            auth_";
  protected final String TEXT_19 = " .setPort(";
  protected final String TEXT_20 = ");" + NL + "            auth_";
  protected final String TEXT_21 = " .setDomain(";
  protected final String TEXT_22 = ");" + NL + "            auth_";
  protected final String TEXT_23 = " .setPreemptiveAuthentication(false);" + NL + "            " + NL + "            options_";
  protected final String TEXT_24 = " .setProperty(org.apache.axis2.transport.http.HTTPConstants.AUTHENTICATE, auth_";
  protected final String TEXT_25 = ");" + NL + "           \toptions_";
  protected final String TEXT_26 = " .setProperty(org.apache.axis2.transport.http.HTTPConstants.REUSE_HTTP_CLIENT, \"";
  protected final String TEXT_27 = "\");" + NL + "" + NL + "            " + NL + "            options_";
  protected final String TEXT_28 = " .setUserName(";
  protected final String TEXT_29 = ");" + NL + "            options_";
  protected final String TEXT_30 = " .setPassword(";
  protected final String TEXT_31 = ");" + NL + "            options_";
  protected final String TEXT_32 = " .setTimeOutInMilliSeconds(Long.valueOf(";
  protected final String TEXT_33 = "));" + NL + "            " + NL + "            options_";
  protected final String TEXT_34 = " .setProperty(org.apache.axis2.transport.http.HTTPConstants.SO_TIMEOUT,new Integer(";
  protected final String TEXT_35 = "));" + NL + "            options_";
  protected final String TEXT_36 = " .setProperty(org.apache.axis2.transport.http.HTTPConstants.CONNECTION_TIMEOUT, new Integer(";
  protected final String TEXT_37 = "));" + NL + "            " + NL + "            com.microsoft.schemas.crm._2007.webservices.CrmAuthenticationTokenDocument catd_";
  protected final String TEXT_38 = " = com.microsoft.schemas.crm._2007.webservices.CrmAuthenticationTokenDocument.Factory.newInstance();" + NL + "            com.microsoft.schemas.crm._2007.coretypes.CrmAuthenticationToken token_";
  protected final String TEXT_39 = " = com.microsoft.schemas.crm._2007.coretypes.CrmAuthenticationToken.Factory.newInstance();" + NL + "            token_";
  protected final String TEXT_40 = ".setAuthenticationType(0);" + NL + "            token_";
  protected final String TEXT_41 = ".setOrganizationName(";
  protected final String TEXT_42 = ");" + NL + "            catd_";
  protected final String TEXT_43 = ".setCrmAuthenticationToken(token_";
  protected final String TEXT_44 = ");" + NL + "            " + NL + "     \t";
  protected final String TEXT_45 = NL + "        \tcom.microsoft.schemas.crm._2006.query.QueryExpression query_";
  protected final String TEXT_46 = " = com.microsoft.schemas.crm._2006.query.QueryExpression.Factory.newInstance();" + NL + "        \tcom.microsoft.schemas.crm._2006.query.ColumnSet cols_";
  protected final String TEXT_47 = " = com.microsoft.schemas.crm._2006.query.ColumnSet.Factory.newInstance();" + NL + "        \tcom.microsoft.schemas.crm._2006.query.ArrayOfString aos_";
  protected final String TEXT_48 = " = com.microsoft.schemas.crm._2006.query.ArrayOfString.Factory.newInstance();";
  protected final String TEXT_49 = NL + "            \t\tcom.microsoft.schemas.crm._2006.query.ConditionExpression condition_";
  protected final String TEXT_50 = " = com.microsoft.schemas.crm._2006.query.ConditionExpression.Factory.newInstance();" + NL + "            \t\tcondition_";
  protected final String TEXT_51 = ".setAttributeName(\"";
  protected final String TEXT_52 = "\");" + NL + "            \t\tcondition_";
  protected final String TEXT_53 = ".setOperator(com.microsoft.schemas.crm._2006.query.ConditionOperator.Enum.forString(\"";
  protected final String TEXT_54 = "\"));";
  protected final String TEXT_55 = NL + "            \t\t\tcom.microsoft.schemas.crm._2006.query.ArrayOfAnyType values_";
  protected final String TEXT_56 = " = com.microsoft.schemas.crm._2006.query.ArrayOfAnyType.Factory.newInstance();" + NL + "            \t\t\torg.xmlsoap.schemas.soap.encoding.String StringValue_";
  protected final String TEXT_57 = " = org.xmlsoap.schemas.soap.encoding.String.Factory.newInstance();" + NL + "            \t\t\tStringValue_";
  protected final String TEXT_58 = ".setStringValue(";
  protected final String TEXT_59 = ");" + NL + "            \t\t\tvalues_";
  protected final String TEXT_60 = ".setValueArray(new org.xmlsoap.schemas.soap.encoding.String[] { StringValue_";
  protected final String TEXT_61 = " });" + NL + "            \t\t\tcondition_";
  protected final String TEXT_62 = ".setValues(values_";
  protected final String TEXT_63 = ");" + NL + "       \t";
  protected final String TEXT_64 = "\t     " + NL + "        \t\tcom.microsoft.schemas.crm._2006.query.ArrayOfConditionExpression conditions_";
  protected final String TEXT_65 = " = com.microsoft.schemas.crm._2006.query.ArrayOfConditionExpression.Factory.newInstance();" + NL + "        \t\tconditions_";
  protected final String TEXT_66 = ".setConditionArray(new com.microsoft.schemas.crm._2006.query.ConditionExpression[] { ";
  protected final String TEXT_67 = " });";
  protected final String TEXT_68 = NL + "        \t\t\tcom.microsoft.schemas.crm._2006.query.FilterExpression filter_";
  protected final String TEXT_69 = " = com.microsoft.schemas.crm._2006.query.FilterExpression.Factory.newInstance();" + NL + "        \t\t\tfilter_";
  protected final String TEXT_70 = ".setFilterOperator(com.microsoft.schemas.crm._2006.query.LogicalOperator.Enum.forString(\"";
  protected final String TEXT_71 = "\"));" + NL + "        \t\t\tfilter_";
  protected final String TEXT_72 = ".setConditions(conditions_";
  protected final String TEXT_73 = ");" + NL + "        \t\t\tquery_";
  protected final String TEXT_74 = ".setCriteria(filter_";
  protected final String TEXT_75 = ");";
  protected final String TEXT_76 = NL + "     ";
  protected final String TEXT_77 = "\t" + NL + "        \taos_";
  protected final String TEXT_78 = ".setAttributeArray(new String[]{";
  protected final String TEXT_79 = "});" + NL + "        \tcols_";
  protected final String TEXT_80 = ".setAttributes(aos_";
  protected final String TEXT_81 = ");" + NL + "        \tquery_";
  protected final String TEXT_82 = ".setColumnSet(cols_";
  protected final String TEXT_83 = ");" + NL + "        \tquery_";
  protected final String TEXT_84 = ".setEntityName(\"";
  protected final String TEXT_85 = "\");" + NL + "        \t" + NL + "        \tcom.microsoft.schemas.crm._2007.webservices.RetrieveMultipleRequest rmr_";
  protected final String TEXT_86 = " = com.microsoft.schemas.crm._2007.webservices.RetrieveMultipleRequest.Factory.newInstance();" + NL + "        \tcom.microsoft.schemas.crm._2007.webservices.ExecuteDocument.Execute execute_";
  protected final String TEXT_87 = " = com.microsoft.schemas.crm._2007.webservices.ExecuteDocument.Execute.Factory.newInstance();" + NL + "        \tcom.microsoft.schemas.crm._2007.webservices.ExecuteDocument executeDoc_";
  protected final String TEXT_88 = " = com.microsoft.schemas.crm._2007.webservices.ExecuteDocument.Factory.newInstance();" + NL + "        \trmr_";
  protected final String TEXT_89 = ".setReturnDynamicEntities(true);" + NL + "        \trmr_";
  protected final String TEXT_90 = ".setQuery(query_";
  protected final String TEXT_91 = ");" + NL + "        \texecute_";
  protected final String TEXT_92 = ".setRequest(rmr_";
  protected final String TEXT_93 = ");" + NL + "        \texecuteDoc_";
  protected final String TEXT_94 = ".setExecute(execute_";
  protected final String TEXT_95 = ");" + NL + "        \texecuteDoc_";
  protected final String TEXT_96 = " = com.microsoft.schemas.crm._2007.webservices.ExecuteDocument.Factory.parse(executeDoc_";
  protected final String TEXT_97 = ".toString());" + NL + "        \tcom.microsoft.schemas.crm._2007.webservices.ExecuteResponseDocument result_";
  protected final String TEXT_98 = ";" + NL + "        \tboolean fetchMore_";
  protected final String TEXT_99 = " = true;" + NL + "        \twhile (fetchMore_";
  protected final String TEXT_100 = ") {" + NL + "        \t\tresult_";
  protected final String TEXT_101 = " = service_";
  protected final String TEXT_102 = ".execute(executeDoc_";
  protected final String TEXT_103 = ", catd_";
  protected final String TEXT_104 = ", null, null);" + NL + "        \t\tcom.microsoft.schemas.crm._2007.webservices.ExecuteResponseDocument.ExecuteResponse executeResponse_";
  protected final String TEXT_105 = " =  result_";
  protected final String TEXT_106 = ".getExecuteResponse();" + NL + "           \t\tcom.microsoft.schemas.crm._2007.webservices.Response response_";
  protected final String TEXT_107 = " = executeResponse_";
  protected final String TEXT_108 = ".getResponse();" + NL + "        \t\tcom.microsoft.schemas.crm._2007.webservices.RetrieveMultipleResponse rmp_";
  protected final String TEXT_109 = " = (com.microsoft.schemas.crm._2007.webservices.RetrieveMultipleResponse)response_";
  protected final String TEXT_110 = ";" + NL + "        \t\tcom.microsoft.schemas.crm._2006.webservices.BusinessEntityCollection bec_";
  protected final String TEXT_111 = " = rmp_";
  protected final String TEXT_112 = ".getBusinessEntityCollection();" + NL + "        \t\tString pagingCookie_";
  protected final String TEXT_113 = " = bec_";
  protected final String TEXT_114 = ".getPagingCookie();" + NL + "        \t\tfetchMore_";
  protected final String TEXT_115 = " = bec_";
  protected final String TEXT_116 = ".getMoreRecords();" + NL + "        \t\tcom.microsoft.schemas.crm._2006.webservices.ArrayOfBusinessEntity aobe_";
  protected final String TEXT_117 = " = bec_";
  protected final String TEXT_118 = ".getBusinessEntities();" + NL + "        \t\tcom.microsoft.schemas.crm._2006.webservices.BusinessEntity[] entities_";
  protected final String TEXT_119 = " = aobe_";
  protected final String TEXT_120 = ".getBusinessEntityArray();" + NL + "        \t\t" + NL + "        \t\tfor (int i_";
  protected final String TEXT_121 = " = 0; i_";
  protected final String TEXT_122 = " < entities_";
  protected final String TEXT_123 = ".length; i_";
  protected final String TEXT_124 = "++) {" + NL + "                    com.microsoft.schemas.crm._2006.webservices.DynamicEntity dynamicEntity_";
  protected final String TEXT_125 = " = (com.microsoft.schemas.crm._2006.webservices.DynamicEntity)entities_";
  protected final String TEXT_126 = "[i_";
  protected final String TEXT_127 = "];" + NL + "                    com.microsoft.schemas.crm._2006.webservices.DynamicEntity.Properties properties_";
  protected final String TEXT_128 = " = dynamicEntity_";
  protected final String TEXT_129 = ".getProperties();" + NL + "                    com.microsoft.schemas.crm._2006.webservices.Property[] propertyArray_";
  protected final String TEXT_130 = " = properties_";
  protected final String TEXT_131 = ".getPropertyArray();" + NL + "                   \tnb_line_";
  protected final String TEXT_132 = " ++;" + NL + "                    String[] propertyValue_";
  protected final String TEXT_133 = " = new String[propertyArray_";
  protected final String TEXT_134 = ".length];" + NL + "                    String propertyType_";
  protected final String TEXT_135 = ";" + NL + "                    java.util.Map<String,String> propertyMap_";
  protected final String TEXT_136 = " = new java.util.HashMap<String,String>();" + NL + "                    " + NL + "                    for(int j_";
  protected final String TEXT_137 = " = 0; j_";
  protected final String TEXT_138 = " < propertyArray_";
  protected final String TEXT_139 = ".length; j_";
  protected final String TEXT_140 = "++){" + NL + "                    \t" + NL + "                    \tpropertyType_";
  protected final String TEXT_141 = " = propertyArray_";
  protected final String TEXT_142 = "[j_";
  protected final String TEXT_143 = "].schemaType().getShortJavaName();" + NL + "                    \tif(\"CrmBooleanProperty\".equals(propertyType_";
  protected final String TEXT_144 = ")){" + NL + "                    \t\tcom.microsoft.schemas.crm._2006.webservices.CrmBooleanProperty tempProperty_";
  protected final String TEXT_145 = " = (com.microsoft.schemas.crm._2006.webservices.CrmBooleanProperty)propertyArray_";
  protected final String TEXT_146 = "[j_";
  protected final String TEXT_147 = "];" + NL + "                    \t\tpropertyValue_";
  protected final String TEXT_148 = "[j_";
  protected final String TEXT_149 = "] = tempProperty_";
  protected final String TEXT_150 = ".getValue().getStringValue();" + NL + "                    \t\tpropertyMap_";
  protected final String TEXT_151 = ".put(tempProperty_";
  protected final String TEXT_152 = ".getName(),propertyValue_";
  protected final String TEXT_153 = "[j_";
  protected final String TEXT_154 = "]);" + NL + "                    \t}else if(\"CrmDateTimeProperty\".equals(propertyType_";
  protected final String TEXT_155 = ")){" + NL + "                    \t\tcom.microsoft.schemas.crm._2006.webservices.CrmDateTimeProperty tempProperty_";
  protected final String TEXT_156 = " = (com.microsoft.schemas.crm._2006.webservices.CrmDateTimeProperty)propertyArray_";
  protected final String TEXT_157 = "[j_";
  protected final String TEXT_158 = "];" + NL + "\t\t\t\t\t\t\tString tempDateString_";
  protected final String TEXT_159 = " = tempProperty_";
  protected final String TEXT_160 = ".getValue().getStringValue();" + NL + "\t\t\t\t\t\t\t";
  protected final String TEXT_161 = NL + "\t\t\t\t\t\t\ttempDateString_";
  protected final String TEXT_162 = " = tempDateString_";
  protected final String TEXT_163 = ".substring(0, tempDateString_";
  protected final String TEXT_164 = ".lastIndexOf(\":\")) + tempDateString_";
  protected final String TEXT_165 = ".substring(tempDateString_";
  protected final String TEXT_166 = ".lastIndexOf(\":\") + 1);" + NL + "\t\t\t\t\t\t\tpropertyValue_";
  protected final String TEXT_167 = "[j_";
  protected final String TEXT_168 = "] = tempDateString_";
  protected final String TEXT_169 = ";" + NL + "\t\t\t\t\t\t\tpropertyMap_";
  protected final String TEXT_170 = ".put(tempProperty_";
  protected final String TEXT_171 = ".getName(),propertyValue_";
  protected final String TEXT_172 = "[j_";
  protected final String TEXT_173 = "]);" + NL + "                    \t}else if(\"CrmDecimalProperty\".equals(propertyType_";
  protected final String TEXT_174 = ")){" + NL + "                    \t\tcom.microsoft.schemas.crm._2006.webservices.CrmDecimalProperty tempProperty_";
  protected final String TEXT_175 = " = (com.microsoft.schemas.crm._2006.webservices.CrmDecimalProperty)propertyArray_";
  protected final String TEXT_176 = "[j_";
  protected final String TEXT_177 = "];" + NL + "\t\t\t\t\t\t\tpropertyValue_";
  protected final String TEXT_178 = "[j_";
  protected final String TEXT_179 = "] = tempProperty_";
  protected final String TEXT_180 = ".getValue().getStringValue();" + NL + "\t\t\t\t\t\t\tpropertyMap_";
  protected final String TEXT_181 = ".put(tempProperty_";
  protected final String TEXT_182 = ".getName(),propertyValue_";
  protected final String TEXT_183 = "[j_";
  protected final String TEXT_184 = "]);" + NL + "                    \t}else if(\"CrmFloatProperty\".equals(propertyType_";
  protected final String TEXT_185 = ")){" + NL + "                    \t\tcom.microsoft.schemas.crm._2006.webservices.CrmFloatProperty tempProperty_";
  protected final String TEXT_186 = " = (com.microsoft.schemas.crm._2006.webservices.CrmFloatProperty)propertyArray_";
  protected final String TEXT_187 = "[j_";
  protected final String TEXT_188 = "];" + NL + "\t\t\t\t\t\t\tpropertyValue_";
  protected final String TEXT_189 = "[j_";
  protected final String TEXT_190 = "] = tempProperty_";
  protected final String TEXT_191 = ".getValue().getStringValue();" + NL + "\t\t\t\t\t\t\tpropertyMap_";
  protected final String TEXT_192 = ".put(tempProperty_";
  protected final String TEXT_193 = ".getName(),propertyValue_";
  protected final String TEXT_194 = "[j_";
  protected final String TEXT_195 = "]);" + NL + "                    \t}else if(\"CrmMoneyProperty\".equals(propertyType_";
  protected final String TEXT_196 = ")){" + NL + "                    \t\tcom.microsoft.schemas.crm._2006.webservices.CrmMoneyProperty tempProperty_";
  protected final String TEXT_197 = " = (com.microsoft.schemas.crm._2006.webservices.CrmMoneyProperty)propertyArray_";
  protected final String TEXT_198 = "[j_";
  protected final String TEXT_199 = "];" + NL + "\t\t\t\t\t\t\tpropertyValue_";
  protected final String TEXT_200 = "[j_";
  protected final String TEXT_201 = "] = tempProperty_";
  protected final String TEXT_202 = ".getValue().getStringValue();" + NL + "\t\t\t\t\t\t\tpropertyMap_";
  protected final String TEXT_203 = ".put(tempProperty_";
  protected final String TEXT_204 = ".getName(),propertyValue_";
  protected final String TEXT_205 = "[j_";
  protected final String TEXT_206 = "]);" + NL + "\t\t\t\t\t\t}else if(\"CrmNumberProperty\".equals(propertyType_";
  protected final String TEXT_207 = ")){" + NL + "\t\t\t\t\t\t\tcom.microsoft.schemas.crm._2006.webservices.CrmNumberProperty tempProperty_";
  protected final String TEXT_208 = " = (com.microsoft.schemas.crm._2006.webservices.CrmNumberProperty)propertyArray_";
  protected final String TEXT_209 = "[j_";
  protected final String TEXT_210 = "];" + NL + "\t\t\t\t\t\t\tpropertyValue_";
  protected final String TEXT_211 = "[j_";
  protected final String TEXT_212 = "] = tempProperty_";
  protected final String TEXT_213 = ".getValue().getStringValue();" + NL + "\t\t\t\t\t\t\tpropertyMap_";
  protected final String TEXT_214 = ".put(tempProperty_";
  protected final String TEXT_215 = ".getName(),propertyValue_";
  protected final String TEXT_216 = "[j_";
  protected final String TEXT_217 = "]);" + NL + "\t\t\t\t\t\t}else if(\"CustomerProperty\".equals(propertyType_";
  protected final String TEXT_218 = ")){" + NL + "\t\t\t\t\t\t\tcom.microsoft.schemas.crm._2006.webservices.CustomerProperty tempProperty_";
  protected final String TEXT_219 = " = (com.microsoft.schemas.crm._2006.webservices.CustomerProperty)propertyArray_";
  protected final String TEXT_220 = "[j_";
  protected final String TEXT_221 = "];" + NL + "\t\t\t\t\t\t\tpropertyValue_";
  protected final String TEXT_222 = "[j_";
  protected final String TEXT_223 = "] = tempProperty_";
  protected final String TEXT_224 = ".getValue().getStringValue();" + NL + "\t\t\t\t\t\t\tpropertyMap_";
  protected final String TEXT_225 = ".put(tempProperty_";
  protected final String TEXT_226 = ".getName(),propertyValue_";
  protected final String TEXT_227 = "[j_";
  protected final String TEXT_228 = "]);" + NL + "\t\t\t\t\t\t}else if(\"KeyProperty\".equals(propertyType_";
  protected final String TEXT_229 = ")){" + NL + "\t\t\t\t\t\t\tcom.microsoft.schemas.crm._2006.webservices.KeyProperty tempProperty_";
  protected final String TEXT_230 = " = (com.microsoft.schemas.crm._2006.webservices.KeyProperty)propertyArray_";
  protected final String TEXT_231 = "[j_";
  protected final String TEXT_232 = "];" + NL + "\t\t\t\t\t\t\tpropertyValue_";
  protected final String TEXT_233 = "[j_";
  protected final String TEXT_234 = "] = tempProperty_";
  protected final String TEXT_235 = ".getValue().getStringValue();" + NL + "\t\t\t\t\t\t\tpropertyMap_";
  protected final String TEXT_236 = ".put(tempProperty_";
  protected final String TEXT_237 = ".getName(),propertyValue_";
  protected final String TEXT_238 = "[j_";
  protected final String TEXT_239 = "]);" + NL + "\t\t\t\t\t\t}else if(\"LookupProperty\".equals(propertyType_";
  protected final String TEXT_240 = ")){" + NL + "\t\t\t\t\t\t\tcom.microsoft.schemas.crm._2006.webservices.LookupProperty tempProperty_";
  protected final String TEXT_241 = " = (com.microsoft.schemas.crm._2006.webservices.LookupProperty)propertyArray_";
  protected final String TEXT_242 = "[j_";
  protected final String TEXT_243 = "];" + NL + "\t\t\t\t\t\t\tpropertyValue_";
  protected final String TEXT_244 = "[j_";
  protected final String TEXT_245 = "] = tempProperty_";
  protected final String TEXT_246 = ".getValue().getStringValue();" + NL + "\t\t\t\t\t\t\tpropertyMap_";
  protected final String TEXT_247 = ".put(tempProperty_";
  protected final String TEXT_248 = ".getName(),propertyValue_";
  protected final String TEXT_249 = "[j_";
  protected final String TEXT_250 = "]);" + NL + "\t\t\t\t\t\t}else if(\"OwnerProperty\".equals(propertyType_";
  protected final String TEXT_251 = ")){" + NL + "\t\t\t\t\t\t\tcom.microsoft.schemas.crm._2006.webservices.OwnerProperty tempProperty_";
  protected final String TEXT_252 = " = (com.microsoft.schemas.crm._2006.webservices.OwnerProperty)propertyArray_";
  protected final String TEXT_253 = "[j_";
  protected final String TEXT_254 = "];" + NL + "\t\t\t\t\t\t\tpropertyValue_";
  protected final String TEXT_255 = "[j_";
  protected final String TEXT_256 = "] = tempProperty_";
  protected final String TEXT_257 = ".getValue().getStringValue();" + NL + "\t\t\t\t\t\t\tpropertyMap_";
  protected final String TEXT_258 = ".put(tempProperty_";
  protected final String TEXT_259 = ".getName(),propertyValue_";
  protected final String TEXT_260 = "[j_";
  protected final String TEXT_261 = "]);" + NL + "\t\t\t\t\t\t}else if(\"PicklistProperty\".equals(propertyType_";
  protected final String TEXT_262 = ")){" + NL + "\t\t\t\t\t\t\tcom.microsoft.schemas.crm._2006.webservices.PicklistProperty tempProperty_";
  protected final String TEXT_263 = " = (com.microsoft.schemas.crm._2006.webservices.PicklistProperty)propertyArray_";
  protected final String TEXT_264 = "[j_";
  protected final String TEXT_265 = "];" + NL + "\t\t\t\t\t\t\tpropertyValue_";
  protected final String TEXT_266 = "[j_";
  protected final String TEXT_267 = "] = tempProperty_";
  protected final String TEXT_268 = ".getValue().getStringValue();" + NL + "\t\t\t\t\t\t\tpropertyMap_";
  protected final String TEXT_269 = ".put(tempProperty_";
  protected final String TEXT_270 = ".getName(),propertyValue_";
  protected final String TEXT_271 = "[j_";
  protected final String TEXT_272 = "]);" + NL + "\t\t\t\t\t\t}else if(\"StateProperty\".equals(propertyType_";
  protected final String TEXT_273 = ")){" + NL + "\t\t\t\t\t\t\tcom.microsoft.schemas.crm._2006.webservices.StateProperty tempProperty_";
  protected final String TEXT_274 = " = (com.microsoft.schemas.crm._2006.webservices.StateProperty)propertyArray_";
  protected final String TEXT_275 = "[j_";
  protected final String TEXT_276 = "];" + NL + "\t\t\t\t\t\t\tpropertyValue_";
  protected final String TEXT_277 = "[j_";
  protected final String TEXT_278 = "] = tempProperty_";
  protected final String TEXT_279 = ".getValue();" + NL + "\t\t\t\t\t\t\tpropertyMap_";
  protected final String TEXT_280 = ".put(tempProperty_";
  protected final String TEXT_281 = ".getName(),propertyValue_";
  protected final String TEXT_282 = "[j_";
  protected final String TEXT_283 = "]);" + NL + "\t\t\t\t\t\t}else if(\"StatusProperty\".equals(propertyType_";
  protected final String TEXT_284 = ")){" + NL + "\t\t\t\t\t\t\tcom.microsoft.schemas.crm._2006.webservices.StatusProperty tempProperty_";
  protected final String TEXT_285 = " = (com.microsoft.schemas.crm._2006.webservices.StatusProperty)propertyArray_";
  protected final String TEXT_286 = "[j_";
  protected final String TEXT_287 = "];" + NL + "\t\t\t\t\t\t\tpropertyValue_";
  protected final String TEXT_288 = "[j_";
  protected final String TEXT_289 = "] = tempProperty_";
  protected final String TEXT_290 = ".getValue().getStringValue();" + NL + "\t\t\t\t\t\t\tpropertyMap_";
  protected final String TEXT_291 = ".put(tempProperty_";
  protected final String TEXT_292 = ".getName(),propertyValue_";
  protected final String TEXT_293 = "[j_";
  protected final String TEXT_294 = "]);" + NL + "\t\t\t\t\t\t}else if(\"StringProperty\".equals(propertyType_";
  protected final String TEXT_295 = ")){" + NL + "\t\t\t\t\t\t\tcom.microsoft.schemas.crm._2006.webservices.StringProperty tempProperty_";
  protected final String TEXT_296 = " = (com.microsoft.schemas.crm._2006.webservices.StringProperty)propertyArray_";
  protected final String TEXT_297 = "[j_";
  protected final String TEXT_298 = "];" + NL + "\t\t\t\t\t\t\tpropertyValue_";
  protected final String TEXT_299 = "[j_";
  protected final String TEXT_300 = "] = tempProperty_";
  protected final String TEXT_301 = ".getValue();" + NL + "\t\t\t\t\t\t\tpropertyMap_";
  protected final String TEXT_302 = ".put(tempProperty_";
  protected final String TEXT_303 = ".getName(),propertyValue_";
  protected final String TEXT_304 = "[j_";
  protected final String TEXT_305 = "]);" + NL + "\t\t\t\t\t\t}else if(\"UniqueIdentifierProperty\".equals(propertyType_";
  protected final String TEXT_306 = ")){" + NL + "\t\t\t\t\t\t\tcom.microsoft.schemas.crm._2006.webservices.UniqueIdentifierProperty tempProperty_";
  protected final String TEXT_307 = " = (com.microsoft.schemas.crm._2006.webservices.UniqueIdentifierProperty)propertyArray_";
  protected final String TEXT_308 = "[j_";
  protected final String TEXT_309 = "];" + NL + "\t\t\t\t\t\t\tpropertyValue_";
  protected final String TEXT_310 = "[j_";
  protected final String TEXT_311 = "] = tempProperty_";
  protected final String TEXT_312 = ".getValue().getStringValue();" + NL + "\t\t\t\t\t\t\tpropertyMap_";
  protected final String TEXT_313 = ".put(tempProperty_";
  protected final String TEXT_314 = ".getName(),propertyValue_";
  protected final String TEXT_315 = "[j_";
  protected final String TEXT_316 = "]);" + NL + "\t\t\t\t\t\t}" + NL + "                    }";
  protected final String TEXT_317 = NL + "\t\t\t\t\t\t\t" + NL + "\t\t\t\t\t\t\tif(propertyMap_";
  protected final String TEXT_318 = ".get(\"";
  protected final String TEXT_319 = "\")!=null){" + NL + "        \t\t\t\t\t";
  protected final String TEXT_320 = "\t\t\t\t" + NL + "        \t\t\t\t\t\t\t";
  protected final String TEXT_321 = ".";
  protected final String TEXT_322 = " = propertyMap_";
  protected final String TEXT_323 = ".get(\"";
  protected final String TEXT_324 = "\");" + NL + "        \t\t\t\t\t";
  protected final String TEXT_325 = NL + "        \t\t\t\t\t\t\t";
  protected final String TEXT_326 = ".";
  protected final String TEXT_327 = " = ParserUtils.parseTo_Date(propertyMap_";
  protected final String TEXT_328 = ".get(\"";
  protected final String TEXT_329 = "\"), ";
  protected final String TEXT_330 = ");" + NL + "        \t\t\t\t\t";
  protected final String TEXT_331 = NL + "        \t\t\t\t\t\t\t";
  protected final String TEXT_332 = ".";
  protected final String TEXT_333 = " = ParserUtils.parseTo_Double(propertyMap_";
  protected final String TEXT_334 = ".get(\"";
  protected final String TEXT_335 = "\"));" + NL + "        \t\t\t\t\t";
  protected final String TEXT_336 = NL + "        \t\t\t\t\t\t\t";
  protected final String TEXT_337 = ".";
  protected final String TEXT_338 = " = ParserUtils.parseTo_BigDecimal(propertyMap_";
  protected final String TEXT_339 = ".get(\"";
  protected final String TEXT_340 = "\"));" + NL + "        \t\t\t\t\t";
  protected final String TEXT_341 = NL + "        \t\t\t\t\t\t\t";
  protected final String TEXT_342 = ".";
  protected final String TEXT_343 = " = ParserUtils.parseTo_Float(propertyMap_";
  protected final String TEXT_344 = ".get(\"";
  protected final String TEXT_345 = "\"));" + NL + "        \t\t\t\t\t";
  protected final String TEXT_346 = NL + "        \t\t\t\t\t\t\t";
  protected final String TEXT_347 = ".";
  protected final String TEXT_348 = " = ParserUtils.parseTo_Integer(propertyMap_";
  protected final String TEXT_349 = ".get(\"";
  protected final String TEXT_350 = "\"));" + NL + "        \t\t\t\t\t";
  protected final String TEXT_351 = NL + "        \t\t\t\t\t\t\t";
  protected final String TEXT_352 = ".";
  protected final String TEXT_353 = " = ParserUtils.parseTo_Boolean(propertyMap_";
  protected final String TEXT_354 = ".get(\"";
  protected final String TEXT_355 = "\"));" + NL + "        \t\t\t\t\t";
  protected final String TEXT_356 = NL + "        \t\t\t\t\t\t\t";
  protected final String TEXT_357 = ".";
  protected final String TEXT_358 = " = propertyMap_";
  protected final String TEXT_359 = ".get(\"";
  protected final String TEXT_360 = "\");" + NL + "        \t\t\t\t\t";
  protected final String TEXT_361 = "\t\t\t\t\t\t\t" + NL + "        \t\t\t\t\t\t\t";
  protected final String TEXT_362 = ".";
  protected final String TEXT_363 = " = ParserUtils.parseTo_";
  protected final String TEXT_364 = "(propertyMap_";
  protected final String TEXT_365 = ".get(\"";
  protected final String TEXT_366 = "\"));\t" + NL + "        \t\t\t\t\t";
  protected final String TEXT_367 = NL + "        \t\t\t\t\t}else{" + NL + "        \t\t\t\t\t\t";
  protected final String TEXT_368 = ".";
  protected final String TEXT_369 = " = ";
  protected final String TEXT_370 = ";" + NL + "        \t\t\t\t\t}" + NL + "        \t\t\t";
  protected final String TEXT_371 = "\t\t\t" + NL + "\t\t\t\t\t" + NL + "                ";
  protected final String TEXT_372 = NL + "  \t\t" + NL + "        \t";

  public String generate(Object argument)
  {
    final StringBuffer stringBuffer = new StringBuffer();
    
CodeGeneratorArgument codeGenArgument = (CodeGeneratorArgument) argument;
INode node = (INode)codeGenArgument.getArgument();
String cid = node.getUniqueName();

    stringBuffer.append(TEXT_1);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_2);
    
List<IMetadataTable> metadatas = node.getMetadataList();
if ((metadatas != null) && (metadatas.size() > 0)) {
	IMetadataTable metadata = metadatas.get(0);
	
	if (metadata != null) {
	
		List<IMetadataColumn> columnList = metadata.getListColumns();
		int nbSchemaColumns = columnList.size();			
		List<? extends IConnection> outgoingConns = node.getOutgoingSortedConnections();

		// if output columns are defined
		if (nbSchemaColumns > 0 && outgoingConns != null && outgoingConns.size() > 0){
			
			String endpointURL = ElementParameterParser.getValue(node, "__ENDPOINTURL__");
			String orgName = ElementParameterParser.getValue(node, "__ORGNAME__");
			String username = ElementParameterParser.getValue(node, "__USERNAME__");
			String password = ElementParameterParser.getValue(node, "__PASSWORD__");
			String domain = ElementParameterParser.getValue(node, "__DOMAIN__");
			String host = ElementParameterParser.getValue(node, "__HOST__");
			String port = ElementParameterParser.getValue(node, "__PORT__");
			String timeoutSecTemp = ElementParameterParser.getValue(node, "__TIMEOUT__");
			String timeoutSec = (timeoutSecTemp!=null&&!("").equals(timeoutSecTemp))?timeoutSecTemp:"2";
			int timeout = (int)(Double.valueOf(timeoutSec) * 1000);
			boolean reuseHttpClient = ("true").equals(ElementParameterParser.getValue(node,"__REUSE_HTTP_CLIENT__"));

    stringBuffer.append(TEXT_3);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_4);
    stringBuffer.append(endpointURL);
    stringBuffer.append(TEXT_5);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_6);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_7);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_8);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_9);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_10);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_11);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_12);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_13);
    stringBuffer.append(username);
    stringBuffer.append(TEXT_14);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_15);
    stringBuffer.append(password);
    stringBuffer.append(TEXT_16);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_17);
    stringBuffer.append(host);
    stringBuffer.append(TEXT_18);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_19);
    stringBuffer.append(port);
    stringBuffer.append(TEXT_20);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_21);
    stringBuffer.append(domain);
    stringBuffer.append(TEXT_22);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_23);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_24);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_25);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_26);
    stringBuffer.append(reuseHttpClient);
    stringBuffer.append(TEXT_27);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_28);
    stringBuffer.append(username);
    stringBuffer.append(TEXT_29);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_30);
    stringBuffer.append(password);
    stringBuffer.append(TEXT_31);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_32);
    stringBuffer.append(timeout);
    stringBuffer.append(TEXT_33);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_34);
    stringBuffer.append(timeout);
    stringBuffer.append(TEXT_35);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_36);
    stringBuffer.append(timeout);
    stringBuffer.append(TEXT_37);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_38);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_39);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_40);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_41);
    stringBuffer.append(orgName);
    stringBuffer.append(TEXT_42);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_43);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_44);
    
     		String entityname = ElementParameterParser.getValue(node, "__ENTITYNAME__").trim();
     		String customEntityname = ElementParameterParser.getValue(node, "__CUSTOM_ENTITY_NAME__");
     		if("CustomEntity".equals(entityname)){
				entityname = customEntityname.replaceAll("\"","");
			}
     		String entitynamealllower = entityname.toLowerCase();
     		String logical = ElementParameterParser.getValue(node,"__LOGICAL_OP__");
     		List<Map<String, String>> keyColumns = (List<Map<String,String>>)ElementParameterParser.getObjectValue(node, "__CONDITIONS__");
     	
    stringBuffer.append(TEXT_45);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_46);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_47);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_48);
    
        	if(keyColumns.size()>0 ){
            	StringBuffer conditionList = new StringBuffer("");
            	int nbCondition = 0;
            	for(Map<String, String> keyColumn:keyColumns){
            		nbCondition++;
            		String conditionID = cid + "_" + String.valueOf(nbCondition);
        
    stringBuffer.append(TEXT_49);
    stringBuffer.append(conditionID);
    stringBuffer.append(TEXT_50);
    stringBuffer.append(conditionID);
    stringBuffer.append(TEXT_51);
    stringBuffer.append(keyColumn.get("INPUT_COLUMN"));
    stringBuffer.append(TEXT_52);
    stringBuffer.append(conditionID);
    stringBuffer.append(TEXT_53);
    stringBuffer.append(keyColumn.get("OPERATOR"));
    stringBuffer.append(TEXT_54);
    
        			if(!("").equals(keyColumn.get("RVALUE"))){
        
    stringBuffer.append(TEXT_55);
    stringBuffer.append(conditionID);
    stringBuffer.append(TEXT_56);
    stringBuffer.append(conditionID);
    stringBuffer.append(TEXT_57);
    stringBuffer.append(conditionID);
    stringBuffer.append(TEXT_58);
    stringBuffer.append(keyColumn.get("RVALUE"));
    stringBuffer.append(TEXT_59);
    stringBuffer.append(conditionID);
    stringBuffer.append(TEXT_60);
    stringBuffer.append(conditionID);
    stringBuffer.append(TEXT_61);
    stringBuffer.append(conditionID);
    stringBuffer.append(TEXT_62);
    stringBuffer.append(conditionID);
    stringBuffer.append(TEXT_63);
    
            		}
            		conditionList.append("condition_"+conditionID+",");
        		}		
        		conditionList.deleteCharAt(conditionList.lastIndexOf(","));
        
    stringBuffer.append(TEXT_64);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_65);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_66);
    stringBuffer.append(conditionList);
    stringBuffer.append(TEXT_67);
    
        		if(!("").equals(logical)){
        
    stringBuffer.append(TEXT_68);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_69);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_70);
    stringBuffer.append(logical);
    stringBuffer.append(TEXT_71);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_72);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_73);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_74);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_75);
    
        		}
        	}
        
    stringBuffer.append(TEXT_76);
    
        	StringBuilder sb = new StringBuilder("");
        	for(IMetadataColumn column: columnList){
  				sb.append("\"");
  				sb.append(column.getLabel());
  				sb.append("\",");      
        	}	
        	sb.deleteCharAt(sb.lastIndexOf(","));
        	IConnection outgoingConn = outgoingConns.get(0);
			if(outgoingConn.getLineStyle().hasConnectionCategory(IConnectionCategory.DATA)) { 
        
    stringBuffer.append(TEXT_77);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_78);
    stringBuffer.append(sb);
    stringBuffer.append(TEXT_79);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_80);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_81);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_82);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_83);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_84);
    stringBuffer.append(entitynamealllower);
    stringBuffer.append(TEXT_85);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_86);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_87);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_88);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_89);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_90);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_91);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_92);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_93);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_94);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_95);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_96);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_97);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_98);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_99);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_100);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_101);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_102);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_103);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_104);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_105);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_106);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_107);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_108);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_109);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_110);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_111);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_112);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_113);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_114);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_115);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_116);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_117);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_118);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_119);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_120);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_121);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_122);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_123);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_124);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_125);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_126);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_127);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_128);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_129);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_130);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_131);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_132);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_133);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_134);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_135);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_136);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_137);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_138);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_139);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_140);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_141);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_142);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_143);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_144);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_145);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_146);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_147);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_148);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_149);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_150);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_151);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_152);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_153);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_154);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_155);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_156);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_157);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_158);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_159);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_160);
    //2009-04-14T10:09:42-07:00 ---> 2009-04-14T10:09:42-0700
    stringBuffer.append(TEXT_161);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_162);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_163);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_164);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_165);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_166);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_167);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_168);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_169);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_170);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_171);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_172);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_173);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_174);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_175);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_176);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_177);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_178);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_179);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_180);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_181);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_182);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_183);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_184);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_185);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_186);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_187);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_188);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_189);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_190);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_191);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_192);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_193);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_194);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_195);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_196);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_197);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_198);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_199);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_200);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_201);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_202);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_203);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_204);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_205);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_206);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_207);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_208);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_209);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_210);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_211);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_212);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_213);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_214);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_215);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_216);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_217);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_218);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_219);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_220);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_221);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_222);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_223);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_224);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_225);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_226);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_227);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_228);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_229);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_230);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_231);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_232);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_233);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_234);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_235);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_236);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_237);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_238);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_239);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_240);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_241);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_242);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_243);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_244);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_245);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_246);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_247);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_248);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_249);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_250);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_251);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_252);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_253);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_254);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_255);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_256);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_257);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_258);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_259);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_260);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_261);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_262);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_263);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_264);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_265);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_266);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_267);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_268);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_269);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_270);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_271);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_272);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_273);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_274);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_275);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_276);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_277);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_278);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_279);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_280);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_281);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_282);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_283);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_284);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_285);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_286);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_287);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_288);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_289);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_290);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_291);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_292);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_293);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_294);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_295);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_296);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_297);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_298);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_299);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_300);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_301);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_302);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_303);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_304);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_305);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_306);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_307);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_308);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_309);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_310);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_311);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_312);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_313);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_314);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_315);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_316);
    
						for( int i = 0; i < columnList.size(); i++) {
						
							IMetadataColumn column = columnList.get(i);
							
							String typeToGenerate = JavaTypesManager.getTypeToGenerate(column.getTalendType(), column.isNullable());
							
							JavaType javaType = JavaTypesManager.getJavaTypeFromId(column.getTalendType());
							
							String patternValue = column.getPattern() == null || column.getPattern().trim().length() == 0 ? null : column.getPattern();
					
    stringBuffer.append(TEXT_317);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_318);
    stringBuffer.append(column.getLabel());
    stringBuffer.append(TEXT_319);
    							
        						if (javaType == JavaTypesManager.STRING) {
        					
    stringBuffer.append(TEXT_320);
    stringBuffer.append(outgoingConn.getName());
    stringBuffer.append(TEXT_321);
    stringBuffer.append(columnList.get(i).getLabel());
    stringBuffer.append(TEXT_322);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_323);
    stringBuffer.append(column.getLabel());
    stringBuffer.append(TEXT_324);
    
        						} else if(javaType == JavaTypesManager.DATE) { // Date
        					
    stringBuffer.append(TEXT_325);
    stringBuffer.append(outgoingConn.getName());
    stringBuffer.append(TEXT_326);
    stringBuffer.append(columnList.get(i).getLabel());
    stringBuffer.append(TEXT_327);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_328);
    stringBuffer.append(column.getLabel());
    stringBuffer.append(TEXT_329);
    stringBuffer.append( patternValue );
    stringBuffer.append(TEXT_330);
    
        						} else if(javaType == JavaTypesManager.DOUBLE) { // Double
        					
    stringBuffer.append(TEXT_331);
    stringBuffer.append(outgoingConn.getName());
    stringBuffer.append(TEXT_332);
    stringBuffer.append(columnList.get(i).getLabel());
    stringBuffer.append(TEXT_333);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_334);
    stringBuffer.append(column.getLabel());
    stringBuffer.append(TEXT_335);
    
        						} else if(javaType == JavaTypesManager.BIGDECIMAL) { // BigDecimal
        					
    stringBuffer.append(TEXT_336);
    stringBuffer.append(outgoingConn.getName());
    stringBuffer.append(TEXT_337);
    stringBuffer.append(columnList.get(i).getLabel());
    stringBuffer.append(TEXT_338);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_339);
    stringBuffer.append(column.getLabel());
    stringBuffer.append(TEXT_340);
    
        						} else if(javaType == JavaTypesManager.FLOAT) { // Float
        					
    stringBuffer.append(TEXT_341);
    stringBuffer.append(outgoingConn.getName());
    stringBuffer.append(TEXT_342);
    stringBuffer.append(columnList.get(i).getLabel());
    stringBuffer.append(TEXT_343);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_344);
    stringBuffer.append(column.getLabel());
    stringBuffer.append(TEXT_345);
    
        						} else if(javaType == JavaTypesManager.INTEGER) { // Integer
        					
    stringBuffer.append(TEXT_346);
    stringBuffer.append(outgoingConn.getName());
    stringBuffer.append(TEXT_347);
    stringBuffer.append(columnList.get(i).getLabel());
    stringBuffer.append(TEXT_348);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_349);
    stringBuffer.append(column.getLabel());
    stringBuffer.append(TEXT_350);
    
        						} else if(javaType == JavaTypesManager.BOOLEAN) { // Boolean
        					
    stringBuffer.append(TEXT_351);
    stringBuffer.append(outgoingConn.getName());
    stringBuffer.append(TEXT_352);
    stringBuffer.append(columnList.get(i).getLabel());
    stringBuffer.append(TEXT_353);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_354);
    stringBuffer.append(column.getLabel());
    stringBuffer.append(TEXT_355);
    
        						} else if(javaType == JavaTypesManager.OBJECT) { // OBJECT
        					
    stringBuffer.append(TEXT_356);
    stringBuffer.append(outgoingConn.getName());
    stringBuffer.append(TEXT_357);
    stringBuffer.append(columnList.get(i).getLabel());
    stringBuffer.append(TEXT_358);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_359);
    stringBuffer.append(column.getLabel());
    stringBuffer.append(TEXT_360);
    
        						} else  { // other
        					
    stringBuffer.append(TEXT_361);
    stringBuffer.append(outgoingConn.getName());
    stringBuffer.append(TEXT_362);
    stringBuffer.append(columnList.get(i).getLabel());
    stringBuffer.append(TEXT_363);
    stringBuffer.append( typeToGenerate );
    stringBuffer.append(TEXT_364);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_365);
    stringBuffer.append(column.getLabel());
    stringBuffer.append(TEXT_366);
    
        						}
        					
    stringBuffer.append(TEXT_367);
    stringBuffer.append(outgoingConn.getName());
    stringBuffer.append(TEXT_368);
    stringBuffer.append(columnList.get(i).getLabel());
    stringBuffer.append(TEXT_369);
    stringBuffer.append(JavaTypesManager.getDefaultValueFromJavaType(typeToGenerate));
    stringBuffer.append(TEXT_370);
    
						}	
					
    stringBuffer.append(TEXT_371);
    
			}		
		}
	}
}

    stringBuffer.append(TEXT_372);
    return stringBuffer.toString();
  }
}
